services:
  - type: web
    name: eduplatform
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: app.settings
      - key: PYTHON_VERSION
        value: 3.11
    plan: free
